
package com.java.servicedescription;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessengerService", targetNamespace = "http://services.java.com/", wsdlLocation = "http://localhost:3456/ws/messenger?wsdl")
public class MessengerService
    extends Service
{

    private final static URL MESSENGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSENGERSERVICE_EXCEPTION;
    private final static QName MESSENGERSERVICE_QNAME = new QName("http://services.java.com/", "MessengerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3456/ws/messenger?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSENGERSERVICE_WSDL_LOCATION = url;
        MESSENGERSERVICE_EXCEPTION = e;
    }

    public MessengerService() {
        super(__getWsdlLocation(), MESSENGERSERVICE_QNAME);
    }

    public MessengerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSENGERSERVICE_QNAME, features);
    }

    public MessengerService(URL wsdlLocation) {
        super(wsdlLocation, MESSENGERSERVICE_QNAME);
    }

    public MessengerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSENGERSERVICE_QNAME, features);
    }

    public MessengerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessengerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Messenger
     */
    @WebEndpoint(name = "MessengerPort")
    public Messenger getMessengerPort() {
        return super.getPort(new QName("http://services.java.com/", "MessengerPort"), Messenger.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Messenger
     */
    @WebEndpoint(name = "MessengerPort")
    public Messenger getMessengerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.java.com/", "MessengerPort"), Messenger.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSENGERSERVICE_EXCEPTION!= null) {
            throw MESSENGERSERVICE_EXCEPTION;
        }
        return MESSENGERSERVICE_WSDL_LOCATION;
    }

}
