
package com.java.clientapp.servicedescription;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://services.helloworldserviceapp.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greetings", targetNamespace = "http://services.helloworldserviceapp.java.com/", className = "com.java.clientapp.servicedescription.Greetings")
    @ResponseWrapper(localName = "greetingsResponse", targetNamespace = "http://services.helloworldserviceapp.java.com/", className = "com.java.clientapp.servicedescription.GreetingsResponse")
    @Action(input = "http://services.helloworldserviceapp.java.com/HelloWorld/greetingsRequest", output = "http://services.helloworldserviceapp.java.com/HelloWorld/greetingsResponse")
    public String greetings(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
